name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [18,19,20]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    
    - name: Install dependencies
      run: |
        npm install

    - name: Start Metro server
      run: npm start &

    - name: CI
      run: npm ci

    - name: Install React Native CLI
      run: npm install -g react-native-cli
      
    - name: Bundle React Native app  
      run: react-native bundle --entry-file index.js --platform android --dev false --bundle-output android/app/src/main/assets/index.android.bundle